name: Generate filter

on:
  push:
    branches:
      - main

    paths:
      - '**/*.txt'

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Build filter generator
        run: go build main.go

      - name: Generate URL filter
        run: |
          mkdir dist
          ./main -punycode -template template/url_google.txt -list list/url_google.txt -output dist/filter.txt

      - name: Generate keyword filter
        run: ./main -template template/keyword_google.txt -list list/keywords_google.txt -output dist/filter.txt

      - name: Generate Twitter filter
        run: ./main -template template/keyword_twitter.txt -list list/keywords_twitter.txt -output dist/filter.txt

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: generate

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
