name: Generate filter

on:
  push:
    branches:
      - main

    paths:
      - keywords.txt
      - mylist.txt

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Build filter generator
        run: go build main.go

      - name: Generate URL filter
        run: |
          mkdir dist
          ./main -punycode -template 'google.*##.g:has(a[href*="%s"]),google.*###Odp5De:has(a[href*="%s"])' -list mylist.txt -output dist/filter.txt

      - name: Generate keyword filter
        run: ./main -template 'google.*##.AUiS2 a:has-text(%s),google.*##.k8XOCe:has-text(%s)' -list keywords.txt -output dist/filter.txt

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/

  deploy:
    needs: generate

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
